### ISSUE TITLE
Question: Will this support keepass/keeweb databases

### ISSUE THREAD

**Issue by arshubham** [BharatKalluri/Easypass#13]
I am trying to leave the Keeweb and finally ditch all electron apps for good but there is no decent looking alternative.

**Comment by BharatKalluri** [comment]
Keeweb essentially works with kdbx files. So, Yes. Easypass can edit and manage your database!

All you need to do is go to settings -> save to -> File and save it on your local machine somewhere.

Then you can open that file in Easypass. I would advice to keep the file in some folder that syncs to Dropbox. So that it will always stay up to date!

If you find any bugs feel free to report them here :)

**Comment by BharatKalluri** [comment]
If everything works, close this issue

**Comment by arshubham** [comment]
Yeah, opens it fine. Just have few issues. will open a new one.
